#!/usr/bin/env bash
set -euo pipefail

echo "Running benchmark: build"
tests/bench-radar/build/run

echo "Running benchmark: size"
tests/bench-radar/size/run

echo "Running benchmark: benchlib"
tests/bench-radar/benchlib/run
